name: Build & test
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install g++ compiler
        run: sudo apt-get install g++
      - name: Run bash script
        run: bash scripts/tests-ubuntu.sh

