name: Build & Test
on: [push, pull_request]
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # required for accessing files in the repository
      - name: Run test.sh
        run: cd ted/ted && bash scripts/test.sh
        # if the script exits with a non-zero value, the workflow will fail
