name: Build & Test
on: [push]
strategy:
  matrix:
    compiler: [gcc, clang]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run test.sh
      env:
        CC: ${{ matrix.compiler }}
      run: bash scripts/test.sh
